// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "./components/Header";
// import Footer from "./components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased `}
//       >
//         <Header />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "WorldStar Packaging Industry",
  description:
    "At WorldStar Packaging, we are proud to be India's largest paper cup manufacturer and exporter, with over 27 years of experience delivering premium packaging solutions. Our expertise spans across RTD (Ready-to-Drink) packaging, serving a wide spectrum of businesses, from iconic Indian brands to global clients.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div id="smooth-wrapper">
          <div
            id="smooth-content"
            className="bg-[#5FBBB5] text-[#17252a] font-dm-sans text-base sm:text-lg leading-[1.5] min-h-screen"
          >
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
